name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build the application
      run: npm run build --if-present
    - name: Run unit tests
      run: npm run test:unit
    
    - name: Install Cypress
      run: npm install cypress --save-dev

    - name: Start server and run Cypress
      run: npx concurrently --kill-others --success first "npm run dev" "npx wait-on http://localhost:3000 && npx cypress run"
